train_path = data/datasets/food/train_context.json
valid_path = data/datasets/food/dev_context.json
test_path = data/datasets/food/test_context.json
save_path = outputs/food/checkpoints/
init_eval = False
save_optimizer = False
train_log_iter = 100
final_eval = False
train_batch_size = 8
epochs = 30
neg_entity_count = 5
neg_relation_count = 0
lr = 2e-05
lr_warmup = 0.1
weight_decay = 0.01
max_grad_norm = 1.0
iou_spn = 0.7
iou_classifier = 1.0
iou_weight = True
offset_loss = smoothl1loss
filter_loss = focalloss
entity_loss = focalloss
giou_loss = giouloss
filter_gamma = 2
entity_gamma = 2
offset_loss_weight = 1.0
filter_loss_weight = 1.0
entity_loss_weight = 1.0
giou_loss_weight = 1.0
iou_gamma = 1.0
types_path = data/datasets/food/food_types.json
tokenizer_path = /root/.cache/modelscope/hub/models/AI-ModelScope/bert-base-chinese
window_size = [30]
lowercase = False
sampling_processes = 4
label = food_train
log_path = outputs/food/logs/
store_predictions = False
store_examples = False
example_count = None
debug = False
device_id = 0
model_path = /root/.cache/modelscope/hub/models/AI-ModelScope/bert-base-chinese
model_type = identifier
cpu = False
eval_batch_size = 2
size_embedding = 25
prop_drop = 0.3
freeze_transformer = False
no_overlapping = False
nms = 0.45
lstm_drop = 0.0
lstm_layers = 1
pos_size = 25
spn_filter = 5.0
char_lstm_layers = 1
char_size = 25
char_lstm_drop = 0.0
use_glove = False
use_pos = False
use_char_lstm = False
pool_type = max
use_entity_ctx = False
wordvec_path = data/datasets/food/glove.6B.2d.txt
use_size_embedding = False
reduce_dim = False
bert_before_lstm = False
no_filter = False
no_regressor = False
norm = sigmoid
no_times_count = False
seed = 47
cache_path = None
