train_path = data/datasets/smoke/train_context.json
valid_path = data/datasets/smoke/dev_context.json
save_path = outputs/smoke/checkpoints/
init_eval = False
save_optimizer = False
train_log_iter = 1
final_eval = True
train_batch_size = 1
epochs = 1
neg_entity_count = 2
neg_relation_count = 0
lr = 1e-05
lr_warmup = 0.0
weight_decay = 0.01
max_grad_norm = 1.0
iou_spn = 0.7
iou_classifier = 1.0
iou_weight = True
offset_loss = smoothl1loss
filter_loss = focalloss
entity_loss = focalloss
giou_loss = giouloss
filter_gamma = 2
entity_gamma = 2
offset_loss_weight = 1.0
filter_loss_weight = 1.0
entity_loss_weight = 1.0
giou_loss_weight = 1.0
iou_gamma = 1.0
types_path = data/datasets/smoke/smoke_types.json
tokenizer_path = /root/.cache/modelscope/hub/models/AI-ModelScope/bert-base-chinese
window_size = [0, 1, 2, 3]
lowercase = False
sampling_processes = 0
label = smoke_train
log_path = outputs/smoke/logs/
store_predictions = False
store_examples = False
example_count = None
debug = False
device_id = 0
model_path = /root/.cache/modelscope/hub/models/AI-ModelScope/bert-base-chinese
model_type = identifier
cpu = False
eval_batch_size = 1
size_embedding = 25
prop_drop = 0.1
freeze_transformer = True
no_overlapping = False
nms = 0.45
lstm_drop = 0.0
lstm_layers = 1
pos_size = 25
spn_filter = 2.0
char_lstm_layers = 1
char_size = 25
char_lstm_drop = 0.0
use_glove = True
use_pos = False
use_char_lstm = False
pool_type = max
use_entity_ctx = False
wordvec_path = data/datasets/smoke/glove.6B.2d.txt
use_size_embedding = False
reduce_dim = False
bert_before_lstm = False
no_filter = False
no_regressor = False
norm = sigmoid
no_times_count = False
seed = 47
cache_path = None
