[1]
label = food_per_class_eval
dataset_path = /root/shared-nvme/projects/locate-and-label/data/datasets/food/test_context.json
types_path = /root/shared-nvme/projects/DiffusionNER/data/datasets/food/food_types.json
model_path = /root/shared-nvme/projects/DiffusionNER/outputs/food/checkpoints/food_train/2026-07-03_22:39:06.171418/best_model
tokenizer_path = /root/.cache/modelscope/hub/AI-ModelScope/bert-base-chinese
model_type = diffusionner
log_path = /root/shared-nvme/projects/DiffusionNER/outputs/food/per_class_eval_logs
eval_batch_size = 32
repeat_gt_entities = -1
store_predictions = True
sampling_processes = 4
no_overlapping = False
no_partial_overlapping = True
no_duplicate = False
cls_threshold = 0
boundary_threshold = 0
entity_threshold = 2.5
sampling_timesteps = 5
num_proposals = 60
span_renewal = False
step_ensemble = False
sample_dist_type = normal
seed = 488
lstm_layers = 2
span_attn_layers = 2
wo_self_attn = False
wo_cross_attn = False
split_epoch = 10
prop_drop = 0.1
soi_pooling = lrconcat
pos_type = sine
beta_schedule = cosine
timesteps = 1000
step_embed_type = add
scale = 1.0
extand_noise_spans = concat
pool_type = max
cpu = False
world_size = -1
local_rank = -1
